package ro.myfinance.access.application;

/**
 * Builds the MyFinance representative-invitation email — branded to the application and the inviting
 * accounting firm (tenant), in Romanian (the product's default language). The body embeds the
 * set-password link generated by the identity provider; the app delivers it through the tenant's own
 * email provider so the From identity is the firm's, not a generic provider address.
 */
final class InviteMessageFactory {

    private InviteMessageFactory() {
    }

    /** Subject line, suffixed with the firm name when known. */
    static String subject(String firmName) {
        String firm = blankToNull(firmName);
        return firm == null ? "Invitație în portalul MyFinance" : "Invitație în portalul MyFinance — " + firm;
    }

    /**
     * Plain-text body. {@code repName} and {@code companyName} are optional (a rep may have no name yet, or
     * be invited before a company is named); {@code firmName} falls back to a neutral phrase; {@code link}
     * is the required set-password URL.
     */
    static String body(String firmName, String companyName, String repName, String link) {
        String firm = blankToNull(firmName) == null ? "firma de contabilitate" : firmName.trim();
        String greeting = blankToNull(repName) == null ? "Bună ziua," : "Bună ziua, " + repName.trim() + ",";

        StringBuilder b = new StringBuilder();
        b.append(greeting).append("\n\n");
        b.append("Ați fost invitat(ă) de ").append(firm)
                .append(" să folosiți portalul de contabilitate MyFinance");
        if (blankToNull(companyName) != null) {
            b.append(" pentru ").append(companyName.trim());
        }
        b.append(".\n\n");
        b.append("Pentru a vă seta parola și a accesa contul, deschideți linkul de mai jos:\n");
        b.append(link).append("\n\n");
        b.append("Linkul este valabil o perioadă limitată. ")
                .append("Dacă nu așteptați această invitație, puteți ignora acest mesaj.\n\n");
        b.append("Cu stimă,\n").append(firm).append(" · MyFinance");
        return b.toString();
    }

    private static String blankToNull(String s) {
        return (s == null || s.isBlank()) ? null : s;
    }
}
