// Romanian fiscal residencies — all 103 municipii + 216 orașe (INSSE) plus the 6 București sectors.
// Source: Wikipedia 'List of cities and towns in Romania' (INSSE 2021). Duplicate names carry the county.
export const ROMANIAN_LOCALITIES = [
  "Abrud",
  "Adjud",
  "Agnita",
  "Aiud",
  "Alba Iulia",
  "Alexandria",
  "Aleșd",
  "Amara",
  "Anina",
  "Aninoasa",
  "Arad",
  "Ardud",
  "Avrig",
  "Azuga",
  "Babadag",
  "Bacău",
  "Baia de Aramă",
  "Baia de Arieș",
  "Baia Mare",
  "Baia Sprie",
  "Balș",
  "Baraolt",
  "Bechet",
  "Beclean",
  "Beiuș",
  "Berbești",
  "Berești",
  "Bicaz",
  "Bistrița",
  "Blaj",
  "Bocșa",
  "Boldești-Scăeni",
  "Bolintin-Vale",
  "Borsec",
  "Borșa",
  "Botoșani",
  "Brad",
  "Bragadiru",
  "Brașov",
  "Breaza",
  "Brezoi",
  "Broșteni",
  "Brăila",
  "Bucecea",
  "București (Sector 1)",
  "București (Sector 2)",
  "București (Sector 3)",
  "București (Sector 4)",
  "București (Sector 5)",
  "București (Sector 6)",
  "Budești",
  "Buftea",
  "Buhuși",
  "Bumbești-Jiu",
  "Buziaș",
  "Buzău",
  "Bușteni",
  "Bârlad",
  "Băbeni",
  "Băicoi",
  "Băile Govora",
  "Băile Herculane",
  "Băile Olănești",
  "Băile Tușnad",
  "Băilești",
  "Bălan",
  "Bălcești",
  "Cajvana",
  "Calafat",
  "Caracal",
  "Caransebeș",
  "Carei",
  "Cavnic",
  "Cehu Silvaniei",
  "Cernavodă",
  "Chitila",
  "Chișineu-Criș",
  "Ciacova",
  "Cisnădie",
  "Cluj-Napoca",
  "Codlea",
  "Comarnic",
  "Comănești",
  "Constanța",
  "Copșa Mică",
  "Corabia",
  "Costești",
  "Covasna",
  "Craiova",
  "Cristuru Secuiesc",
  "Cugir",
  "Curtea de Argeș",
  "Curtici",
  "Câmpeni",
  "Câmpia Turzii",
  "Câmpina",
  "Câmpulung",
  "Câmpulung Moldovenesc",
  "Călan",
  "Călimănești",
  "Călărași",
  "Căzănești",
  "Darabani",
  "Dej",
  "Deta",
  "Deva",
  "Dolhasca",
  "Dorohoi",
  "Dragomirești",
  "Drobeta-Turnu Severin",
  "Drăgănești-Olt",
  "Drăgășani",
  "Dumbrăveni",
  "Dăbuleni",
  "Dărmănești",
  "Eforie",
  "Fetești",
  "Fieni",
  "Fierbinți-Târg",
  "Filiași",
  "Flămânzi",
  "Focșani",
  "Frasin",
  "Fundulea",
  "Făget",
  "Făgăraș",
  "Fălticeni",
  "Făurei",
  "Galați",
  "Geoagiu",
  "Gheorgheni",
  "Gherla",
  "Ghimbav",
  "Giurgiu",
  "Gura Humorului",
  "Găești",
  "Gătaia",
  "Hațeg",
  "Horezu",
  "Huedin",
  "Hunedoara",
  "Huși",
  "Hârlău",
  "Hârșova",
  "Ianca",
  "Iași",
  "Iernut",
  "Ineu",
  "Isaccea",
  "Jibou",
  "Jimbolia",
  "Lehliu Gară",
  "Lipova",
  "Liteni",
  "Livada",
  "Luduș",
  "Lugoj",
  "Lupeni",
  "Mangalia",
  "Marghita",
  "Medgidia",
  "Mediaș",
  "Miercurea Ciuc",
  "Miercurea Nirajului",
  "Miercurea Sibiului",
  "Mihăilești",
  "Milișăuți",
  "Mioveni",
  "Mizil",
  "Moinești",
  "Moldova Nouă",
  "Moreni",
  "Motru",
  "Murfatlar",
  "Murgeni",
  "Măcin",
  "Măgurele",
  "Mărășești",
  "Negrești",
  "Negrești-Oaș",
  "Negru Vodă",
  "Nehoiu",
  "Novaci",
  "Nucet",
  "Nădlac",
  "Năsăud",
  "Năvodari",
  "Ocna Mureș",
  "Ocna Sibiului",
  "Ocnele Mari",
  "Odobești",
  "Odorheiu Secuiesc",
  "Oltenița",
  "Onești",
  "Oradea",
  "Oravița",
  "Orăștie",
  "Orșova",
  "Otopeni",
  "Ovidiu",
  "Oțelu Roșu",
  "Panciu",
  "Pantelimon",
  "Pașcani",
  "Pecica",
  "Petrila",
  "Petroșani",
  "Piatra Neamț",
  "Piatra-Olt",
  "Pitești",
  "Ploiești",
  "Plopeni",
  "Podu Iloaiei",
  "Pogoanele",
  "Popești-Leordeni",
  "Potcoava",
  "Predeal",
  "Pucioasa",
  "Pâncota",
  "Pătârlagele",
  "Recaș",
  "Reghin",
  "Reșița",
  "Roman",
  "Rovinari",
  "Roznov",
  "Roșiorii de Vede",
  "Rupea",
  "Râmnicu Sărat",
  "Râmnicu Vâlcea",
  "Râșnov",
  "Răcari",
  "Rădăuți",
  "Salcea",
  "Salonta",
  "Satu Mare",
  "Scornicești",
  "Sebeș",
  "Sebiș",
  "Segarcea",
  "Seini",
  "Sfântu Gheorghe",
  "Sibiu",
  "Sighetu Marmației",
  "Sighișoara",
  "Simeria",
  "Sinaia",
  "Siret",
  "Slatina",
  "Slobozia",
  "Slănic",
  "Slănic Moldova",
  "Solca",
  "Sovata",
  "Strehaia",
  "Suceava",
  "Sulina",
  "Sângeorgiu de Pădure",
  "Sângeorz-Băi",
  "Sânnicolau Mare",
  "Sântana",
  "Săcele",
  "Săcueni",
  "Săliște",
  "Săliștea de Sus",
  "Sărmașu",
  "Săveni",
  "Techirghiol",
  "Tecuci",
  "Teiuș",
  "Timișoara",
  "Tismana",
  "Titu",
  "Toplița",
  "Topoloveni",
  "Tulcea",
  "Turceni",
  "Turda",
  "Turnu Măgurele",
  "Târgoviște",
  "Târgu Bujor",
  "Târgu Cărbunești",
  "Târgu Frumos",
  "Târgu Jiu",
  "Târgu Lăpuș",
  "Târgu Mureș",
  "Târgu Neamț",
  "Târgu Ocna",
  "Târgu Secuiesc",
  "Târnăveni",
  "Tălmaciu",
  "Tăuții-Măgherăuș",
  "Tășnad",
  "Ulmeni",
  "Ungheni",
  "Uricani",
  "Urlați",
  "Urziceni",
  "Valea lui Mihai",
  "Vaslui",
  "Vatra Dornei",
  "Vașcău",
  "Vicovu de Sus",
  "Victoria",
  "Videle",
  "Vișeu de Sus",
  "Vlăhița",
  "Voluntari",
  "Vulcan",
  "Vânju Mare",
  "Vălenii de Munte",
  "Zalău",
  "Zimnicea",
  "Zlatna",
  "Zărnești",
  "Însurăței",
  "Întorsura Buzăului",
  "Șimleu Silvaniei",
  "Șomcuta Mare",
  "Ștefănești (Argeș)",
  "Ștefănești (Botoșani)",
  "Ștei",
  "Țicleni",
  "Țăndărei",
] as const;

export type RomanianLocality = (typeof ROMANIAN_LOCALITIES)[number];
